const CACHE_NAME='pegsetting-v1-'+Date.now();
self.addEventListener('install',e=>{
  e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll([
    './',
    './index.html',
    './css/style.css',
    './js/app.js',
    './js/admin.js',
    './js/pwa.js',
    './data.json',
    './manifest.json'
  ])));
});
self.addEventListener('activate',e=>{
  e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))));
});
self.addEventListener('fetch',e=>{
  e.respondWith(fetch(e.request).catch(()=>caches.match(e.request)));
});
